services:
  blockchain:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-node
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    command: npx hardhat node
    networks:
      - cvb-network

  blockchain-tests:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-tests
    depends_on:
      - blockchain
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    entrypoint: npx hardhat test

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - BLOCKCHAIN_URL=http://blockchain-node:8545
    depends_on:
      - blockchain
    networks:
      - cvb-network

  database:
    image: postgres:18.0-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cvb_user
      - POSTGRES_PASSWORD=cvb_password
      - POSTGRES_DB=cvb_db
    networks:
      - cvb-network

networks:
  cvb-network:
    driver: bridge

volumes:
  db-data:
