services:
  blockchain:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-node
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    command: npx hardhat node --port 8545 --hostname 0.0.0.0
    networks:
      - cvb-network

  blockchain-tests:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-tests
    depends_on:
      - blockchain
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    entrypoint: npx hardhat test

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./blockchain/artifacts/contracts:/abi
    environment:
      - BLOCKCHAIN_URL=http://blockchain:8545
    depends_on:
      - blockchain
    networks:
      - cvb-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cvb-network

  database:
    image: postgres:18.0-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cvb_user
      - POSTGRES_PASSWORD=cvb_password
      - POSTGRES_DB=cvb_db
    networks:
      - cvb-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - cvb-network

networks:
  cvb-network:
    driver: bridge

volumes:
  db-data:
  minio-data:
