services:
  traefik:
    container_name: cvb-traefik
    image: traefik:v3.6.2
    env_file:
      - .env
    ports:
      - "${TRAEFIK_WEB_PORT}:80"
      - "${TRAEFIK_WEB_SECURE_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - traefik_ssl_certs:/ssl-certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${APPLICATION_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=staging"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - cvb-network
    restart: always

  nginx:
    image: ghcr.io/JomarJunior/cvb-frontend:latest
    container_name: nginx-frontend
    expose:
      - "80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`cvb.159.65.243.11.nip.io`) && PathPrefix(`/certificado-verde-blockchain`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=staging"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.middlewares.stripcertificado.stripprefix.prefixes=/certificado-verde-blockchain"
      - "traefik.http.routers.nginx.middlewares=stripcertificado"
    networks:
      - cvb-network
    restart: always

  blockchain:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-node
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    command: npx hardhat node --port 8545 --hostname 0.0.0.0 --network hardhat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cvb-network

  blockchain-deploy:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-deploy
    depends_on:
      - blockchain
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    entrypoint: npx hardhat run scripts/deploy.js --network docker
    networks:
      - cvb-network

  blockchain-tests:
    build:
      context: blockchain
      dockerfile: Dockerfile
    container_name: blockchain-tests
    depends_on:
      - blockchain
    volumes:
      - ./blockchain:/app
      - /app/node_modules
    entrypoint: npx hardhat test

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./blockchain/artifacts/contracts:/abi
    environment:
      - BLOCKCHAIN_URL=http://blockchain:8545
    depends_on:
      - blockchain
    networks:
      - cvb-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - cvb-network

  database:
    image: postgres:18.0-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cvb_user
      - POSTGRES_PASSWORD=cvb_password
      - POSTGRES_DB=cvb_db
    networks:
      - cvb-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - cvb-network

networks:
  cvb-network:
    driver: bridge

volumes:
  db-data:
  minio-data:
  traefik_ssl_certs:
    driver: local